### ISSUE TITLE
register existing groups in dyngroups system

### ISSUE THREAD

**Issue by nomisum** [gruppe-adler/TvT_Rattenfalle.rhspkl#80]

**Comment by McDiod** [comment]
I guess this is not working because the init box of a unit's editor attributes is executed before the initX.sqf scripts are, so it's trying to register the groups before the dynamic groups system is initialized.

**Comment by nomisum** [comment]
should be fixed in https://github.com/gruppe-adler/TvT_Rattenfalle.rhspkl/commit/1ebe1761912d617a1d9445fc128a5b052c945ce3
